### ISSUE TITLE
Default units for energies and lengths in YAML input

### ISSUE THREAD

**Issue by brainandforce** [xamberl/DFT-raMO#33]
As I've reading through the `read_run_yaml` code, I've come to realize that the default interpretation of energy values depends on the choice of software package. This may not require a significant change, but I figure explicitly considering the solutions to this issue is a good idea, especially if others plan to rerun calculations with different software packages.

There are three options to consider:
1. Infer the energy unit from the software package (if `software: vasp` then assume the input is in eV, if `software: abinit` then assume hartree). This is the behavior as coded.
2. Use a default energy unit for DFT-raMO (probably Hartree, as with Electrum and most DFT packages) and allow for users to specify a different unit if desired. `emax: 9.5` would be interpreted as 9.5 hartree by default.
3. Require that an energy unit is specified every time. An entry like `emax: 9.5` would be invalid, and an error would be thrown to indicate this.

If we want to stick with the first option, feel free to close the issue. However, we should add support for alternative units in the YAML regardless.

**Comment by xamberl** [comment]
I prefer inferring the energy, as I suspect users who are familiar in VASP would prefer to use eV (due to information in the output files). Same for Ha and ABINIT users. In this case, I would prefer to leave it as is (option 1).

When you say alternative units, @brainandforce, what energy units are you talking about?

**Comment by brainandforce** [comment]
I just mean that a user should be able to provide an entry like `emax: 9.5 eV` to indicate that the units are not to be inferred from the choice of software package.

**Comment by xamberl** [comment]
Yes, they should be able to do that. https://github.com/xamberl/DFT-raMO/blob/c3830565db8a7eddd95d84b407816cc8641e912f/src/inputs.jl#L143C1-L154C4

**Comment by brainandforce** [comment]
Not sure if you saw my edit above, but does unit specification also work for lengths?

**Comment by xamberl** [comment]
No, currently there are no unit specifications for lengths. This one feels a little trickier: as DFT-raMO is intended to make _molecular_ analogies, I think what would be best is to implement Angstroms as the default, but for consistency, perhaps we should also have it infer that if we're using ABINIT, that Bohr is the default unless specified otherwise. Thoughts?

**Comment by brainandforce** [comment]
I agree, we should try to keep the units consistent with the `software` key if we're inferring them contextually.

This is more of a technical note, but for identifying valid unit expressions we can use regex instead of string equality. I'll likely implement this at some point in the future.

**Comment by brainandforce** [comment]
Has this been implemented with the merging of #39?
